parameters:
    image_workshop.web_root: '%kernel.root_dir%/../web'

services:
    image_workshop.factory:
        class: JDecool\Bundle\ImageWorkshopBundle\Factory\ImageLayerFactory

    image_workshop.manager:
        class: JDecool\Bundle\ImageWorkshopBundle\Services\ImageManager
        arguments:
            - '@image_workshop.factory'
            - []

    image_workshop.cache_resolver:
        class: JDecool\Bundle\ImageWorkshopBundle\Services\CacheManager
        arguments:
            - '@router.request_context'
            - '@image_workshop.manager'
            - '%image_workshop.web_root%'
            - '%image_workshop.cache_prefix%'
            - '%image_workshop.cache_lifetime%'

    image_workshop.twig_extension:
        class: JDecool\Bundle\ImageWorkshopBundle\Twig\ImageWorkshopExtension
        arguments:
            - '@image_workshop.cache_resolver'
        tags:
            - { name: twig.extension }
