language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.5.*

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer selfupdate
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer update

script:
  - vendor/bin/atoum
