language: php

php:
  - 5.7
  - 5.6
  - 5.5
  - 5.4
  - hhvm-nightly

env:
  - SYMFONY_VERSION=2.7.*@dev
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.5.*

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm-nightly

before_script:
  - composer selfupdate
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer update

script:
  - vendor/bin/atoum
